version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
    deploy:
        docker:
            - image: node:latest
        steps:
            - checkout
            - run:
                name: Install
                command: npm install 
            - run:
                name: Test
                command: npm test
            - run:
                name: Install Serverless
                command: npm install -g serverless 
            - run:
                name: Serverless Configuration
                command: serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
            - run:
                name: Deploy
                command: npm run deploy
        
workflows:
  node-tests:
    tests:
      - deploy
      # - node/test

      