version: 2.1
orbs:
  node: circleci/node@3.0.0
  aws-serverless: circleci/aws-serverless@1.0.2
  

workflows:
  node-tests:
    jobs:
      - node/test
      - aws-serverless/deploy:
          name: deploy-staging
          stack-name: staging-stack
          template: ../serverless.yml
          s3-bucket: $AWS_ARTIFACT_BUCKET
          requires:
            - node/test
