version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
    deploy:
        docker:
            - image: node:latest
        steps:
            - checkout
            - run:
                name: Install
                command: npm install 
            - run:
                name: Test
                command: npm test
            


workflows:
  node-tests:
    jobs:
      - deploy
      # - node/test

      